import { defectTypes, severities, initialFilters } from "../constants";
import { useInspectionTracker } from "../hooks/useInspectionTracker";
import { formatDate, SeverityBadge, FieldLabel } from "../utils/common";

export default function InspectionTracker({ onLogout }) {
  const {
    form, filters, setFilters, setAppliedFilters, inspections, summary,
    isLoading, isSubmitting, error, notice, resolving, setResolving,
    resolutionNote, setResolutionNote, totalOpen, totalResolved,
    updateForm, updateFilter, handleCreate, handleResolve,
  } = useInspectionTracker();

  return <main className="min-h-screen bg-slate-50 text-slate-950">
    <header className="bg-gradient-to-br from-blue-950 via-blue-900 to-indigo-900 px-4 pb-12 pt-6 text-white sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white/15 text-xl ring-1 ring-white/20">✓</div><div><p className="text-xs font-bold tracking-[0.18em] text-blue-200">ARVIND LIMITED</p><h1 className="text-lg font-bold">Quality Tracker</h1></div></div><div className="flex items-center gap-3"><span className="rounded-full bg-emerald-400/15 px-3 py-1.5 text-xs font-semibold text-emerald-200 ring-1 ring-emerald-300/30">● Live log</span><button type="button" onClick={onLogout} className="text-xs font-semibold text-blue-100 hover:text-white cursor-pointer">Sign out</button></div></div><div className="mt-8 max-w-xl"><p className="text-sm font-medium text-blue-200">Shop-floor quality control</p><h2 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Spot it. Log it. Resolve it.</h2><p className="mt-2 text-sm leading-6 text-blue-100">Keep every fabric-quality issue visible from the line to resolution.</p></div></div></header>

    <div className="mx-auto -mt-7 max-w-6xl px-4 pb-10 sm:px-6"><section aria-label="Inspection summary" className="grid grid-cols-2 gap-3 lg:grid-cols-5"><article className="col-span-2 rounded-2xl bg-white p-4 shadow-lg shadow-blue-950/10 ring-1 ring-slate-200 lg:col-span-2"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Current overview</p><div className="mt-3 flex items-end gap-7"><div><p className="text-3xl font-black text-slate-900">{totalOpen}</p><p className="text-xs font-semibold text-slate-500">Open issues</p></div><div><p className="text-3xl font-black text-emerald-600">{totalResolved}</p><p className="text-xs font-semibold text-slate-500">Resolved</p></div></div></article>{summary.map((item) => <article key={item.severity} className="rounded-2xl bg-white p-4 shadow-lg shadow-blue-950/10 ring-1 ring-slate-200"><SeverityBadge severity={item.severity} /><div className="mt-3 flex gap-3 text-sm"><span><b>{item.open}</b> <small className="text-slate-500">open</small></span><span><b className="text-emerald-600">{item.resolved}</b> <small className="text-slate-500">done</small></span></div></article>)}</section>
      {(error || notice) && <div role="status" className={`mt-5 rounded-xl border px-4 py-3 text-sm font-medium ${error ? "border-rose-200 bg-rose-50 text-rose-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{error || notice}</div>}
      <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,0.85fr)_minmax(0,1.35fr)]"><section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">New record</p><h2 className="mt-1 text-xl font-bold">Log an inspection</h2></div><span className="grid size-9 place-items-center rounded-xl bg-blue-50 text-lg">+</span></div><form className="mt-5 space-y-4" onSubmit={handleCreate}><div className="grid grid-cols-2 gap-3"><div><FieldLabel htmlFor="inspectionDate">Inspection date</FieldLabel><input id="inspectionDate" name="inspectionDate" type="date" value={form.inspectionDate} onChange={updateForm} required className="input" /></div><div><FieldLabel htmlFor="machineLineId">Machine / line</FieldLabel><input id="machineLineId" name="machineLineId" placeholder="e.g. Loom-03" value={form.machineLineId} onChange={updateForm} required className="input" /></div></div><div><FieldLabel htmlFor="defectType">Defect type</FieldLabel><select id="defectType" name="defectType" value={form.defectType} onChange={updateForm} className="input">{defectTypes.map((type) => <option key={type}>{type}</option>)}</select></div><div><FieldLabel htmlFor="severity">Severity</FieldLabel><select id="severity" name="severity" value={form.severity} onChange={updateForm} className="input">{severities.map((severity) => <option key={severity}>{severity}</option>)}</select></div><div><FieldLabel htmlFor="remarks">Remarks <span className="font-normal text-slate-400">(optional)</span></FieldLabel><textarea id="remarks" name="remarks" rows="3" placeholder="What did you observe?" value={form.remarks} onChange={updateForm} className="input resize-none" /></div><button disabled={isSubmitting} className="w-full rounded-xl bg-blue-700 px-4 py-3.5 text-sm font-bold text-white shadow-sm hover:bg-blue-800 disabled:opacity-60">{isSubmitting ? "Saving…" : "Log inspection"}</button></form></section>
        <section className="min-w-0"><div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Live register</p><h2 className="mt-1 text-xl font-bold">Inspection log</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{inspections.length} showing</span></div><form onSubmit={(event) => { event.preventDefault(); setAppliedFilters(filters); }} className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><select aria-label="Filter by severity" name="severity" value={filters.severity} onChange={updateFilter} className="input"><option value="">All severities</option>{severities.map((severity) => <option key={severity}>{severity}</option>)}</select><select aria-label="Filter by status" name="status" value={filters.status} onChange={updateFilter} className="input"><option value="">All statuses</option><option>Open</option><option>Resolved</option></select><select aria-label="Sort inspections" name="sortBy" value={filters.sortBy} onChange={updateFilter} className="input"><option value="inspectionDate">Sort: inspection date</option><option value="createdAt">Sort: created time</option><option value="severity">Sort: severity</option><option value="machineLineId">Sort: machine / line</option></select><input aria-label="From date" name="from" type="date" value={filters.from} onChange={updateFilter} className="input" /><input aria-label="To date" name="to" type="date" value={filters.to} onChange={updateFilter} className="input" /><div className="flex gap-2"><button className="flex-1 rounded-xl bg-slate-900 px-3 py-2.5 text-sm font-bold text-white">Apply</button><button type="button" onClick={() => { setFilters(initialFilters); setAppliedFilters(initialFilters); }} className="rounded-xl px-3 text-sm font-bold text-slate-600 hover:bg-slate-100">Reset</button></div></form></div>
          <div className="mt-4 space-y-3">{isLoading && <div className="rounded-2xl bg-white p-8 text-center text-sm font-medium text-slate-500 shadow-sm ring-1 ring-slate-200">Loading inspections…</div>}{!isLoading && inspections.length === 0 && <div className="rounded-2xl bg-white p-8 text-center shadow-sm ring-1 ring-slate-200"><p className="text-2xl">◎</p><h3 className="mt-2 font-bold">No inspections found</h3><p className="mt-1 text-sm text-slate-500">Log a new inspection or clear the filters.</p></div>}{!isLoading && inspections.map((inspection) => <article key={inspection.id} className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><SeverityBadge severity={inspection.severity} /><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${inspection.status === "Open" ? "bg-violet-100 text-violet-700" : "bg-emerald-100 text-emerald-700"}`}>{inspection.status}</span></div><h3 className="mt-3 font-bold">{inspection.defectType}</h3><p className="mt-1 text-sm text-slate-500">{inspection.machineLineId} · {formatDate(inspection.inspectionDate)}</p></div><span className="text-xs font-bold text-slate-400">#{inspection.id}</span></div>{inspection.remarks && <p className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-sm leading-5 text-slate-600">{inspection.remarks}</p>}{inspection.status === "Resolved" && <p className="mt-3 text-sm text-emerald-700"><span className="font-bold">Resolution:</span> {inspection.resolutionNote}</p>}{inspection.status === "Open" && <button onClick={() => { setResolving(inspection); setResolutionNote(""); }} className="mt-4 min-h-11 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white hover:bg-emerald-700">Mark resolved</button>}</article>)}</div></section></div></div>
    {resolving && <div className="fixed inset-0 z-20 flex items-end bg-slate-950/40 p-0 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="resolve-title"><form onSubmit={handleResolve} className="w-full rounded-t-3xl bg-white p-6 shadow-2xl sm:max-w-md sm:rounded-3xl"><div className="mx-auto h-1.5 w-12 rounded-full bg-slate-200 sm:hidden" /><p className="mt-4 text-xs font-bold uppercase tracking-wider text-emerald-700">Close the loop</p><h2 id="resolve-title" className="mt-1 text-xl font-bold">Resolve inspection #{resolving.id}</h2><p className="mt-2 text-sm text-slate-600">Add the action taken for {resolving.machineLineId}. This note is required.</p><textarea autoFocus required value={resolutionNote} onChange={(event) => setResolutionNote(event.target.value)} rows="4" placeholder="Describe the fix and verification…" className="input mt-4 resize-none" /><div className="mt-4 flex gap-3"><button type="button" onClick={() => setResolving(null)} className="min-h-12 flex-1 rounded-xl bg-slate-100 px-4 text-sm font-bold text-slate-700">Cancel</button><button disabled={isSubmitting} className="min-h-12 flex-1 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white disabled:opacity-60">{isSubmitting ? "Saving…" : "Resolve"}</button></div></form></div>}
  </main>;
}